cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'little-angry-clouds/homebrew-my-brews'
tap 'mike-engel/jwt-cli'
tap 'dty1er/tap'

brew 'asdf'
brew 'zsh'
brew 'ack'
brew 'coreutils'
brew 'ctags'
brew 'derailed/k9s/k9s'
brew 'docker-credential-helper-ecr'
brew 'fzf'
brew 'grc'
brew 'helmenv'
brew 'htop'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'jwt-cli'
brew 'kafkacat'
brew 'kubecolor'
# brew 'libcaca'
brew 'libgit2'
brew 'openssl'
brew 'readline'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'terraform-docs'
brew 'wget'
brew 'yq'
brew 'youtube-dl'
brew 'global'
brew 'gpg'
brew 'git'
brew 'git-crypt'
brew 'hub'
brew 'vim'

brew 'dnsmasq'

# brew 'rbenv'

cask 'caffeine'
cask 'dbeaver-community'

# cask 'adium'
# cask 'atom'
# cask 'firefox'
# cask 'google-chrome'
# cask 'handbrake'
# cask 'seashore'
# cask 'slack'
# cask 'transmission'
# cask 'tunnelbear'
# cask 'vlc'
